version: '3'

services:
  go-db-data-run:
    container_name: db-data-c
    build: .
    command: go run main.go
    volumes:
      - ./:/go/src/app
    working_dir: /go/src/app
    ports:
      - "3030:3000"
    environment:
      PORT: 3001